# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Digital_IC/Digital_IC_Lab/Lab2_VGA_4096/Lab2_VGA_4096.srcs/sources_1/ip/clk_25M/clk_25M.xci
# IP: The module: 'clk_25M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Digital_IC/Digital_IC_Lab/Lab2_VGA_4096/Lab2_VGA_4096.srcs/sources_1/ip/clk_25M/clk_25M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25M'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Digital_IC/Digital_IC_Lab/Lab2_VGA_4096/Lab2_VGA_4096.srcs/sources_1/ip/clk_25M/clk_25M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Digital_IC/Digital_IC_Lab/Lab2_VGA_4096/Lab2_VGA_4096.srcs/sources_1/ip/clk_25M/clk_25M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/Digital_IC/Digital_IC_Lab/Lab2_VGA_4096/Lab2_VGA_4096.srcs/sources_1/ip/clk_25M/clk_25M.xci
# IP: The module: 'clk_25M' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Digital_IC/Digital_IC_Lab/Lab2_VGA_4096/Lab2_VGA_4096.srcs/sources_1/ip/clk_25M/clk_25M_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Digital_IC/Digital_IC_Lab/Lab2_VGA_4096/Lab2_VGA_4096.srcs/sources_1/ip/clk_25M/clk_25M.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Digital_IC/Digital_IC_Lab/Lab2_VGA_4096/Lab2_VGA_4096.srcs/sources_1/ip/clk_25M/clk_25M_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_25M'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
