# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 16
set_param chipscope.maxJobs 4
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/Lab4_INTERRUPT.cache/wt [current_project]
set_property parent.project_path D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/Lab4_INTERRUPT.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/Lab4_INTERRUPT.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_BRAM/AHB2BRAM.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_BUS/AHBDCD.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_GPIO/AHBGPIO.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_BUS/AHBMUX.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_TIMER/AHBTIMER.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_UART/AHBUART.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_VGA/AHBVGASYS.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/CortexM3-DS/CORTEXM3INTEGRATIONDS.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_UART/baudgen.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_VGA/counter.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_VGA/dual_port_ram_sync.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_UART/fifo.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_VGA/font_rom.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_TIMER/prescaler.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_UART/uart_rx.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_UART/uart_tx.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_VGA/vga_console.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_VGA/vga_image.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/AHB_VGA/vga_sync.v
  D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/ARMSOC_TOP.v
}
read_ip -quiet D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/Lab4_INTERRUPT.srcs/sources_1/ip/clk_50M/clk_50M.xci
set_property used_in_implementation false [get_files -all d:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/Lab4_INTERRUPT.srcs/sources_1/ip/clk_50M/clk_50M_board.xdc]
set_property used_in_implementation false [get_files -all d:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/Lab4_INTERRUPT.srcs/sources_1/ip/clk_50M/clk_50M.xdc]
set_property used_in_implementation false [get_files -all d:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/Lab4_INTERRUPT.srcs/sources_1/ip/clk_50M/clk_50M_ooc.xdc]

read_ip -quiet D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/Lab4_INTERRUPT.srcs/sources_1/ip/clk_25M/clk_25M.xci
set_property used_in_implementation false [get_files -all d:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/Lab4_INTERRUPT.srcs/sources_1/ip/clk_25M/clk_25M_board.xdc]
set_property used_in_implementation false [get_files -all d:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/Lab4_INTERRUPT.srcs/sources_1/ip/clk_25M/clk_25M.xdc]
set_property used_in_implementation false [get_files -all d:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/Lab4_INTERRUPT.srcs/sources_1/ip/clk_25M/clk_25M_ooc.xdc]

read_edif D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/CortexM3-DS/CORTEXM3INTEGRATIONDS.edf
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/ARMSOC.xdc
set_property used_in_implementation false [get_files D:/Digital_IC/Digital_IC_Lab/Lab4_INTERRUPT/FPGA/ARMSOC.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ARMSOC_TOP -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ARMSOC_TOP.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ARMSOC_TOP_utilization_synth.rpt -pb ARMSOC_TOP_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
