set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN T5 [get_ports CLK]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} -add [get_ports CLK]

set_property IOSTANDARD LVCMOS33 [get_ports RESET]
set_property PACKAGE_PIN P15 [get_ports RESET]

set_property IOSTANDARD LVCMOS33 [get_ports TCK]
set_property IOSTANDARD LVCMOS33 [get_ports TDI]
set_property IOSTANDARD LVCMOS33 [get_ports TDO]
set_property IOSTANDARD LVCMOS33 [get_ports TMS]
set_property SLEW FAST [get_ports TDO]
set_property SLEW FAST [get_ports TMS]
set_property PACKAGE_PIN G18 [get_ports TMS]
set_property PACKAGE_PIN J17 [get_ports TDI]
set_property PACKAGE_PIN J18 [get_ports TDO]
set_property PACKAGE_PIN F18 [get_ports TCK]
create_clock -period 40.000 -name dbg_tck_pin -waveform {0.000 20.000} -add [get_ports TCK]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets TCK]

# set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
# set_property PACKAGE_PIN U16 [get_ports {LED[7]}]
# set_property PACKAGE_PIN U17 [get_ports {LED[6]}]
# set_property PACKAGE_PIN V17 [get_ports {LED[5]}]
# set_property PACKAGE_PIN R18 [get_ports {LED[4]}]
# set_property PACKAGE_PIN N14 [get_ports {LED[3]}]
# set_property PACKAGE_PIN J13 [get_ports {LED[2]}]
# set_property PACKAGE_PIN K15 [get_ports {LED[1]}]
# set_property PACKAGE_PIN H17 [get_ports {LED[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports VGA_HSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports VGA_VSYNC]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RED[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_GREEN[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_GREEN[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_GREEN[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_BLUE[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {VGA_BLUE[0]}]
set_property SLEW FAST [get_ports VGA_HSYNC]
set_property SLEW FAST [get_ports VGA_VSYNC]
set_property SLEW FAST [get_ports {VGA_RED[2]}]
set_property SLEW FAST [get_ports {VGA_RED[1]}]
set_property SLEW FAST [get_ports {VGA_RED[0]}]
set_property SLEW FAST [get_ports {VGA_GREEN[2]}]
set_property SLEW FAST [get_ports {VGA_GREEN[1]}]
set_property SLEW FAST [get_ports {VGA_GREEN[0]}]
set_property SLEW FAST [get_ports {VGA_BLUE[1]}]
set_property SLEW FAST [get_ports {VGA_BLUE[0]}]
set_property PACKAGE_PIN D7 [get_ports VGA_HSYNC]
set_property PACKAGE_PIN C4 [get_ports VGA_VSYNC]
set_property PACKAGE_PIN B7 [get_ports {VGA_RED[2]}]
set_property PACKAGE_PIN C5 [get_ports {VGA_RED[1]}]
set_property PACKAGE_PIN C6 [get_ports {VGA_RED[0]}]
set_property PACKAGE_PIN D8 [get_ports {VGA_GREEN[2]}]
set_property PACKAGE_PIN A5 [get_ports {VGA_GREEN[1]}]
set_property PACKAGE_PIN A6 [get_ports {VGA_GREEN[0]}]
set_property PACKAGE_PIN E7 [get_ports {VGA_BLUE[1]}]
set_property PACKAGE_PIN E5 [get_ports {VGA_BLUE[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports UART_RXD]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TXD]
set_property PACKAGE_PIN N5 [get_ports UART_RXD]
set_property PACKAGE_PIN T4 [get_ports UART_TXD]

# set_property IOSTANDARD LVCMOS33 [get_ports VGA_HSYNC]
# set_property IOSTANDARD LVCMOS33 [get_ports VGA_VSYNC]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RED[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RED[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RED[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_RED[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_GREEN[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_GREEN[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_GREEN[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_GREEN[0]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_BLUE[3]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_BLUE[2]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_BLUE[1]}]
# set_property IOSTANDARD LVCMOS33 [get_ports {VGA_BLUE[0]}]
# set_property SLEW FAST [get_ports VGA_HSYNC]
# set_property SLEW FAST [get_ports VGA_VSYNC]
# set_property SLEW FAST [get_ports {VGA_RED[3]}]
# set_property SLEW FAST [get_ports {VGA_RED[2]}]
# set_property SLEW FAST [get_ports {VGA_RED[1]}]
# set_property SLEW FAST [get_ports {VGA_RED[0]}]
# set_property SLEW FAST [get_ports {VGA_GREEN[3]}]
# set_property SLEW FAST [get_ports {VGA_GREEN[2]}]
# set_property SLEW FAST [get_ports {VGA_GREEN[1]}]
# set_property SLEW FAST [get_ports {VGA_GREEN[0]}]
# set_property SLEW FAST [get_ports {VGA_BLUE[3]}]
# set_property SLEW FAST [get_ports {VGA_BLUE[2]}]
# set_property SLEW FAST [get_ports {VGA_BLUE[1]}]
# set_property SLEW FAST [get_ports {VGA_BLUE[0]}]
# set_property PACKAGE_PIN D7 [get_ports VGA_HSYNC]
# set_property PACKAGE_PIN C4 [get_ports VGA_VSYNC]
# set_property PACKAGE_PIN B7 [get_ports {VGA_RED[3]}]
# set_property PACKAGE_PIN C5 [get_ports {VGA_RED[2]}]
# set_property PACKAGE_PIN C6 [get_ports {VGA_RED[1]}]
# set_property PACKAGE_PIN F5 [get_ports {VGA_RED[0]}]
# set_property PACKAGE_PIN D8 [get_ports {VGA_GREEN[3]}]
# set_property PACKAGE_PIN A5 [get_ports {VGA_GREEN[2]}]
# set_property PACKAGE_PIN A6 [get_ports {VGA_GREEN[1]}]
# set_property PACKAGE_PIN B6 [get_ports {VGA_GREEN[0]}]
# set_property PACKAGE_PIN E7 [get_ports {VGA_BLUE[3]}]
# set_property PACKAGE_PIN E5 [get_ports {VGA_BLUE[2]}]
# set_property PACKAGE_PIN E6 [get_ports {VGA_BLUE[1]}]
# set_property PACKAGE_PIN C7 [get_ports {VGA_BLUE[0]}]
