# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Digital_IC/Digital_IC_Lab/Lab3_UART/FPGA/ARMSOC.xdc

# IP: ip/clk_25M/clk_25M.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_25M || ORIG_REF_NAME==clk_25M} -quiet] -quiet
